s = "NEESESESWNSWEWNWESWSWEWWWEESNWESWWWNSNNNNWNSNEWWESSNNENNWESEWEEWNNNSNWSENSSWSEWWSWWNSSNNNSSNENSENESENSSSEWSSWNEEWSEWNSENWWSSSNWNSNEWNENESNSNSSSEWEEWSEEWEENNWSEWESESESWSENESWSENENESEWSEWEWNESNSNWWWSWEE"

print(s.count("N") - s.count("S"))
print(s.count("E") - s.count("W"))